spring:
  application:
    name: mall
  thymeleaf:
    cache: false
  datasource:
    # 1. ????? log4jdbc??? ??
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # 2. url ??? 'log4jdbc'? ??? ??
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/shopping_mall
    username: root
    password: zxcvasqw!2

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.shopping.mall.domain

file:
  upload-dir: D:/upload

# 3. ?? ?? ?? (log4jdbc ??)
logging:
  level:
    root: info
    log4jdbc.log4j2: error
    jdbc.sqlonly: info     # ??? SQL? ??
    jdbc.sqltiming: off   # SQL ?? ?? ??
    jdbc.resultsettable: off # ???(Result Set)? ??? ???? ??
    jdbc.audit: off        # ?? ??? ??? ?
    jdbc.resultset: off    # ResultSet ???? ?? ??? ?
    jdbc.connection: off   # ??? ??/?? ?? ?